// Category lists + chip tooltips, shared by /status/ and /status/new/.
// Any sxiva code missing from HOBBY_CATEGORIES/WORK_CATEGORIES counts as "Other".
const HOBBY_CATEGORIES = ['wf', 'wr', 'bkc', 'arch', 'ean', 'ff', 'fw', 'gtr', 'hg', 'hu', 'math', 'mus', 'phy', 'prg', 'read', 'vip', 'ws', 'qt', 'life', 'cs', 'act', 'rk', 'ky', 'agi', 'wapp', 'fesh', 'wrs', 'wre', 'wrf', 'wri', 'wrj', 'wro', 'wrr', 'wrt', 'drc', 'wdfr', 'ms', 'su', 'art', 'cbc'];
const WORK_CATEGORIES = ['sp'];

// Tag descriptions shown in the category chip tooltips (kept lowercase)
const TAG_INFO = {
    abi: 'things for abi, e.g. halloween decoration',
    act: 'activism: learning how best to help',
    art: 'painting, etc.',
    drc: 'dopamine resistance counter',
    err: 'errands',
    fam: 'family',
    fin: 'finances',
    fit: 'workout',
    fun: 'fun, e.g. super metroid rom-hacking',
    help: 'helping friends move, etc.',
    hw: 'halloween',
    jnl: 'journalling',
    rel: 'relationships (friends, neighbors, etc.)',
    rv: '2026 rv trip across america',
    sys: 'daily tracking system and organization, e.g. sxiva',
    agi: 'abi goh illustrations (website)',
    arch: 'arch linux: customization, maintenance, optimization. daily workflows: [wf]',
    bkc: 'book club (reading and meetings)',
    cbc: 'cat bap cup',
    cs: 'computer science',
    ean: 'enemies and neighbors (history of israel & palestine)',
    fesh: 'fesh (workout app)',
    ff: 'flash fiction (course)',
    fw: 'fiction writing (course)',
    gtr: 'guitar (non-band)',
    hg: 'haunting ghosts (practice and shows)',
    hu: 'humanitarian (studies, volunteering)',
    ky: 'kathy yuan (websites)',
    life: 'life (reflection, realignment)',
    math: 'math, e.g. finding kaprekar constants in other bases',
    ms: 'manuscript studio (renamed from [wrs])',
    mus: 'music (general)',
    phy: 'physics',
    prg: 'programming',
    qt: 'quantum theory',
    read: 'non-book club reading',
    rk: 'ronnie kichurchak (reviewing and editing his book)',
    su: 'startup',
    vip: 'voices of israel and palestine (personal project showcasing peace efforts of both sides)',
    wapp: 'renamed [fesh] (workout app)',
    wdfr: 'the wildfire (novel)',
    wf: 'daily workflows: optimization and development, e.g. sxiva',
    wr: 'writing (mainly "the wildfire" from 12/4/25, separated to [wdfr])',
    wre: 'writing/editing',
    wrf: 'writing/feedback',
    wri: 'writing/ideation',
    wrj: 'writing/journalling',
    wro: 'writing/organization',
    wrr: 'writing (review)',
    wrs: 'writing system: renamed manuscript studio [ms]',
    wrt: 'writing (technique)',
    ws: 'personal website'
};
