// Bundle html/hxh/os + html/hxh/apps into ONE served file per page load:
//   html/hxh/hxh.js  (IIFE, global `HxH`)  + hxh.css + source maps.
// Deterministic, unminified (readable in devtools). Run via `npm run build`;
// tests/bundle.test.js fails when the committed bundle is stale.
import { buildSync } from "esbuild";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
export const entry = path.join(root, "html/hxh/os/index.js");
export const outfile = path.join(root, "html/hxh/hxh.js");

export function bundle({ write = true } = {}) {
  return buildSync({
    entryPoints: [entry],
    bundle: true,
    format: "iife",
    globalName: "HxH",
    outfile,
    sourcemap: true,
    sourcesContent: false,
    target: ["es2022"],
    legalComments: "none",
    logLevel: "silent",
    banner: { js: "/* GENERATED by `npm run build` from html/hxh/os + apps — do not edit. */", css: "/* GENERATED by `npm run build` from html/hxh/os/os.css + apps/*.css — do not edit. */" },
    write,
  });
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const r = bundle();
  if (r.errors.length) { console.error(r.errors); process.exit(1); }
  console.log("built html/hxh/hxh.js + hxh.css");
}
