#!/usr/bin/tclsh

set output ""

append output "{"
append output [format {
  "title": "Karabiner settings generated by install-karabiner-settings.tcl.",
  "rules": [}]

append output [format {
    {
      "description": "Change caps_lock to left_command except when pressed alone (then change to escape).",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "caps_lock",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_command"
            }
          ],
          "to_if_alone": [
            {
              "key_code": "escape"
            }
          ]
        }
      ]
    },
    {
      "description": "Change left_command to hyper (command+control+option+shift).",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "left_command",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_shift",
              "modifiers": [
                "left_command",
                "left_control",
                "left_option"
              ]
            }
          ]
        }
      ]
    }}]

foreach key {z n} {
    append output [format {,
    {
      "description": "Emulate command+control+%s for Evernote with control+option+%s.",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "%s",
            "modifiers": {
              "mandatory": [
                "left_control",
                "left_option"
              ]
            }
          },
          "to": [
            {
              "key_code": "%s",
              "modifiers": [
                "left_command",
                "left_control"
              ]
            }
          ]
        }
      ]
    }} $key $key $key $key]
}

foreach key {left_arrow right_arrow up_arrow down_arrow} {
    append output [format {,
    {
      "description": "Passthrough hyper+%s to command+option+%s.",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "%s",
            "modifiers": {
              "mandatory": [
                "left_shift",
                "left_command",
                "left_control",
                "left_option"
              ]
            }
          },
          "to": [
            {
              "key_code": "%s",
              "modifiers": [
                "left_command",
                "left_option"
              ]
            }
          ]
        }
      ]
    }} $key $key $key $key]
}

append output "\n  ]\n}"

puts $output
